# Generated by Django 4.1.6 on 2023-02-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_body_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
    ]
