# Generated by Django 4.1.7 on 2023-04-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'DR'), ('Published', 'PB')], default='Draft', max_length=20),
        ),
    ]
