# Generated by Django 5.0 on 2023-12-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='25-may.jpg', null=True, upload_to='blog/images/'),
        ),
    ]
