# Generated by Django 5.0 on 2023-12-27 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('bday', models.DateField(blank=True, null=True)),
                ('dday', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('author_image', models.ImageField(default='default_picture.png', upload_to='authors/')),
                ('birth_place', models.CharField(default='Birth place is not provided', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=17)),
                ('language', models.CharField(default='English', max_length=50)),
                ('published_date', models.DateField()),
                ('pages', models.PositiveIntegerField(default=100)),
                ('cover_pic', models.ImageField(default='default_book_cover.jpg', upload_to='book/')),
            ],
        ),
        migrations.CreateModel(
            name='Editions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=17)),
                ('pages', models.PositiveIntegerField(default=100)),
                ('cover', models.CharField(choices=[('Paperback', 'PB'), ('Kindle edition', 'KE'), ('Hard Cover', 'HC'), ('E-book', 'EB')], default='Paperback', max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('published_date', models.DateField()),
                ('cover_pic', models.ImageField(default='default_book_cover.jpg', upload_to='book/edition')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_shelf', models.CharField(blank=True, choices=[('currently_reading', 'Currently Reading'), ('want_to_read', 'Want to Read'), ('read', 'Read')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookOnShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('stars_given', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
