# Generated by Django 4.1.7 on 2023-03-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=17)),
                ('language', models.CharField(max_length=20)),
                ('published_date', models.DateField()),
                ('cover_pic', models.ImageField(default='default_profile_pic.jpg', upload_to='book/edition')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
