# Generated by Django 4.1.7 on 2023-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_editions'),
    ]

    operations = [
        migrations.AddField(
            model_name='editions',
            name='cover',
            field=models.CharField(choices=[('PB', 'Paperback'), ('KE', 'Kindle_edition'), ('HC', 'Hard_Cover'), ('EB', 'E-book')], default='PB', max_length=50),
        ),
    ]
