# Generated by Django 4.2.7 on 2024-01-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
