# Generated by Django 4.1.7 on 2023-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_editions_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='editions',
            name='pages',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='editions',
            name='cover',
            field=models.CharField(choices=[('PB', 'Paperback'), ('KE', 'Kindle edition'), ('HC', 'Hard Cover'), ('EB', 'E-book')], default='PB', max_length=50),
        ),
    ]
