# Generated by Django 4.0 on 2024-01-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_alter_bookreview_options_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='default_shelf',
        ),
        migrations.AlterField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(through='Books.BookOnShelf', to='Books.Book'),
        ),
    ]
