# Generated by Django 4.1.7 on 2023-04-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_book_pages_editions_pages_alter_editions_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editions',
            name='cover',
            field=models.CharField(choices=[('Paperback', 'PB'), ('Kindle edition', 'KE'), ('Hard Cover', 'HC'), ('E-book', 'EB')], default='Paperback', max_length=50),
        ),
    ]
