# Generated by Django 4.0 on 2024-01-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_bookreview_options_remove_shelf_default_shelf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(to='Books.Book'),
        ),
        migrations.DeleteModel(
            name='BookOnShelf',
        ),
    ]
