# Generated by Django 4.1.7 on 2023-04-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_editions_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editions',
            name='cover_pic',
            field=models.ImageField(default='default_book_cover.jpg', upload_to='book/edition'),
        ),
    ]
