# Generated by Django 4.1.7 on 2023-04-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_editions_cover_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['created_at']},
        ),
    ]
