# Generated by Django 4.1.7 on 2023-04-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_alter_bookreview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-created_at']},
        ),
    ]
