# Generated by Django 4.1.7 on 2023-07-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editions',
            name='pages',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
