# Generated by Django 4.1.7 on 2023-09-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0013_shelf_delete_bookshelves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='book',
        ),
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='shelf',
            name='book',
            field=models.ManyToManyField(to='Books.book'),
        ),
    ]
